version: '3.8'

services:
  # Backend con SymPy + FastAPI
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - solvmath-network

  # Frontend (servidor estático)
  frontend:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - solvmath-network

  # LLM Local con Ollama (opcional)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - solvmath-network
    profiles:
      - llm  # Solo se ejecuta con --profile llm

volumes:
  ollama_data:
    driver: local

networks:
  solvmath-network:
    driver: bridge

